[project]
title = "MCUBoot Requirements"

features = [
  # Stable features.
  "TABLE_SCREEN",
  "TRACEABILITY_SCREEN",
  "DEEP_TRACEABILITY_SCREEN",

  "MATHJAX",

  # Experimental features are disabled by default.
  # "REQIF",
  # "STANDALONE_DOCUMENT_SCREEN",
  # "REQUIREMENTS_COVERAGE_SCREEN",
  "REQUIREMENT_TO_SOURCE_TRACEABILITY",
  # "HTML2PDF",
]