name: Docs

on: [push]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: sudo apt-get install --reinstall python3-pkg-resources

      - run: pip install strictdoc

      - if: github.ref == 'refs/heads/sysrs' || startsWith(github.ref, 'refs/tags/v')
        run: |
          strictdoc export .
          cp output/html /tmp/strictdoc
          git checkout gh-pages
          cp /tmp/strictdoc .
          git add .
          git commit -m "Updated docs"
          git push